name: nahj_balagha_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.3
dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  dio: ^5.9.2
  equatable: ^2.0.8
  firebase_core: ^4.9.0
  firebase_messaging: ^16.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.2.4
  get_it: ^9.2.1
  jwt_decoder: ^2.0.1
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  device_preview: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
          weight: 400
          style: normal

        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 700
          style: normal
